# Generated by Django 3.1.2 on 2020-11-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_docs', models.ImageField(upload_to='docs_img/')),
                ('categorie', models.CharField(choices=[('SOLUTIONS', 'SOLUTIONS'), ('PRODUITS', 'PRODUITS'), ('PARTENAIRES', 'PARTENAIRES'), ('INVESTISSEURS', 'INVESTISSEURS')], max_length=300)),
                ('question', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('reponse', models.TextField()),
            ],
        ),
    ]
