# Generated by Django 3.1.6 on 2021-02-18 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='reponse',
            field=tinymce.models.HTMLField(verbose_name='reponse'),
        ),
    ]
