# Generated by Django 3.1.2 on 2020-10-30 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='img_docs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='docs_img/'),
            preserve_default=False,
        ),
    ]
