# Generated by Django 3.1.6 on 2021-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0002_auto_20210218_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='reponse',
            field=models.TextField(),
        ),
    ]
