# Generated by Django 3.1.6 on 2021-02-18 13:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0003_auto_20210218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='reponse',
            field=tinymce.models.HTMLField(verbose_name='reponse'),
        ),
    ]
