# Generated by Django 3.1.2 on 2020-10-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='annonce_img/')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Commerciale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='commerciale/')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fidelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='fidelite_img/')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forms_Artisans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('telephone_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='artisans_img/')),
                ('date', models.DateTimeField()),
                ('adresse', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forms_Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('telephone_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='consulant_img/')),
                ('date', models.DateTimeField()),
                ('adresse', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forms_Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('telephone_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='entreprise_img/')),
                ('rccm', models.CharField(max_length=300)),
                ('id_nat', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('adresse', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forms_Investisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('telephone_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='investisseur_img/')),
                ('adresse', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forms_Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('telephone_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='partenaire_img/')),
                ('adresse', models.CharField(max_length=300)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='marketing_img/')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('secteur', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='opportunite_img/')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
