# Generated by Django 3.1.2 on 2020-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_artisans',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forms_artisans',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_consultant',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forms_consultant',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_entreprise',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forms_entreprise',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_investisseur',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forms_partenaire',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
