# Generated by Django 3.1.2 on 2020-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201030_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True),
        ),
        migrations.AddField(
            model_name='commerciale',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True),
        ),
        migrations.AddField(
            model_name='fidelite',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True),
        ),
        migrations.AddField(
            model_name='marketing',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True),
        ),
    ]
