# Generated by Django 3.1.4 on 2021-01-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201203_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerciale',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
