# Generated by Django 3.1.2 on 2020-10-31 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201030_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms_investisseur',
            old_name='type',
            new_name='motivation',
        ),
        migrations.RemoveField(
            model_name='forms_consultant',
            name='description',
        ),
        migrations.AddField(
            model_name='forms_consultant',
            name='specialite',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='img',
            field=models.ImageField(upload_to='annonce_img/'),
        ),
        migrations.AlterField(
            model_name='commerciale',
            name='img',
            field=models.ImageField(upload_to='commerciale/'),
        ),
        migrations.AlterField(
            model_name='fidelite',
            name='img',
            field=models.ImageField(upload_to='fidelite_img/'),
        ),
        migrations.AlterField(
            model_name='forms_artisans',
            name='logo',
            field=models.ImageField(blank=True, upload_to='artisans_img/'),
        ),
        migrations.AlterField(
            model_name='forms_artisans',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_consultant',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_entreprise',
            name='logo',
            field=models.ImageField(blank=True, upload_to='entreprise_img/'),
        ),
        migrations.AlterField(
            model_name='forms_entreprise',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_investisseur',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='forms_partenaire',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='img',
            field=models.ImageField(upload_to='marketing_img/'),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='img',
            field=models.ImageField(upload_to='opportunite_img/'),
        ),
    ]
