# Generated by Django 3.1.6 on 2021-02-18 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_commerciale_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='commerciale',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='fidelite',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='opportunite',
            name='secteur',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='commerciale',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fidelite',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forms_artisans',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forms_entreprise',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forms_investisseur',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forms_partenaire',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
