# Generated by Django 3.1.2 on 2020-11-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('img_partenaire', models.ImageField(upload_to='partenaire_img/')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
