# Generated by Django 3.1.2 on 2020-10-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisans_solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('secteur_artisans', models.CharField(choices=[('Agroalimentaire', 'Agroalimentaire'), ('Banque / Assurance', 'Banque / Assurance'), ('Bois / Papier / Carton / Imprimerie', 'Bois / Papier / Carton / Imprimerie'), ('BTP / Matériaux de construction', 'BTP / Matériaux de construction'), ('Chimie / Parachimie', 'Chimie / Parachimie'), ('Commerce / Négoce / Distribution', 'Commerce / Négoce / Distribution'), ('Édition / Communication / Multimédia', 'Édition / Communication / Multimédia'), ('Électronique / Électricité', 'Électronique / Électricité'), ('Études et conseils', 'Études et conseils'), ('Industrie pharmaceutique', 'Industrie pharmaceutique'), ('Informatique / Télécoms', 'Informatique / Télécoms'), ('Machines et équipements / Automobile', 'Machines et équipements / Automobile'), ('Métallurgie / Travail du métal', 'Métallurgie / Travail du métal'), ('Plastique / Caoutchouc', 'Plastique / Caoutchouc'), ('Services aux entreprises', 'Services aux entreprises'), ('Textile / Habillement / Chaussure', 'Textile / Habillement / Chaussure'), ('Transports / Logistique', 'Transports / Logistique')], max_length=300)),
                ('fonctions_artisans', models.CharField(max_length=500)),
                ('logo_artisans', models.ImageField(upload_to='entreprise_solution_img/')),
                ('telephone_artisans', models.DecimalField(decimal_places=0, max_digits=13)),
                ('telephone_2_artisans', models.DecimalField(decimal_places=0, max_digits=13)),
                ('email_artisans', models.EmailField(max_length=254)),
                ('description_artisans', models.CharField(max_length=500)),
                ('competence_artisans', models.CharField(max_length=500)),
                ('sociauFB_artisans', models.URLField(blank=True, help_text='Copiez le lien de compte Facebook et collez le ici')),
                ('sociauTW_artisans', models.URLField(blank=True, help_text='Copiez le lien de compte Twitter et collez le ici')),
                ('sociauINS_artisans', models.URLField(blank=True, help_text='Copiez le lien de compte Instagram et collez le ici')),
                ('sociauIN_artisans', models.URLField(blank=True, help_text='Copiez le lien de compte LinkedIN et collez le ici')),
            ],
        ),
        migrations.CreateModel(
            name='Consultance_solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('secteur_consultance', models.CharField(choices=[('Agroalimentaire', 'Agroalimentaire'), ('Banque / Assurance', 'Banque / Assurance'), ('Bois / Papier / Carton / Imprimerie', 'Bois / Papier / Carton / Imprimerie'), ('BTP / Matériaux de construction', 'BTP / Matériaux de construction'), ('Chimie / Parachimie', 'Chimie / Parachimie'), ('Commerce / Négoce / Distribution', 'Commerce / Négoce / Distribution'), ('Édition / Communication / Multimédia', 'Édition / Communication / Multimédia'), ('Électronique / Électricité', 'Électronique / Électricité'), ('Études et conseils', 'Études et conseils'), ('Industrie pharmaceutique', 'Industrie pharmaceutique'), ('Informatique / Télécoms', 'Informatique / Télécoms'), ('Machines et équipements / Automobile', 'Machines et équipements / Automobile'), ('Métallurgie / Travail du métal', 'Métallurgie / Travail du métal'), ('Plastique / Caoutchouc', 'Plastique / Caoutchouc'), ('Services aux entreprises', 'Services aux entreprises'), ('Textile / Habillement / Chaussure', 'Textile / Habillement / Chaussure'), ('Transports / Logistique', 'Transports / Logistique')], max_length=300)),
                ('fonctions_consultance', models.CharField(max_length=500)),
                ('logo_consultance', models.ImageField(upload_to='entreprise_solution_img/')),
                ('telephone_consultance', models.DecimalField(decimal_places=0, max_digits=13)),
                ('telephone_2_consultance', models.DecimalField(decimal_places=0, max_digits=13)),
                ('email_consultance', models.EmailField(max_length=254)),
                ('description_consultance', models.CharField(max_length=500)),
                ('competence_consultance', models.CharField(max_length=500)),
                ('sociauFB_consultance', models.URLField(blank=True, help_text='Copiez le lien de compte Facebook et collez le ici')),
                ('sociauTW_consultance', models.URLField(blank=True, help_text='Copiez le lien de compte Twitter et collez le ici')),
                ('sociauINS_consultance', models.URLField(blank=True, help_text='Copiez le lien de compte Instagram et collez le ici')),
                ('sociauIN_consultance', models.URLField(blank=True, help_text='Copiez le lien de compte LinkedIN et collez le ici')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise_solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('secteur_entreprise', models.CharField(choices=[('Agroalimentaire', 'Agroalimentaire'), ('Banque / Assurance', 'Banque / Assurance'), ('Bois / Papier / Carton / Imprimerie', 'Bois / Papier / Carton / Imprimerie'), ('BTP / Matériaux de construction', 'BTP / Matériaux de construction'), ('Chimie / Parachimie', 'Chimie / Parachimie'), ('Commerce / Négoce / Distribution', 'Commerce / Négoce / Distribution'), ('Édition / Communication / Multimédia', 'Édition / Communication / Multimédia'), ('Électronique / Électricité', 'Électronique / Électricité'), ('Études et conseils', 'Études et conseils'), ('Industrie pharmaceutique', 'Industrie pharmaceutique'), ('Informatique / Télécoms', 'Informatique / Télécoms'), ('Machines et équipements / Automobile', 'Machines et équipements / Automobile'), ('Métallurgie / Travail du métal', 'Métallurgie / Travail du métal'), ('Plastique / Caoutchouc', 'Plastique / Caoutchouc'), ('Services aux entreprises', 'Services aux entreprises'), ('Textile / Habillement / Chaussure', 'Textile / Habillement / Chaussure'), ('Transports / Logistique', 'Transports / Logistique')], max_length=300)),
                ('fonctions_entreprise', models.CharField(max_length=500)),
                ('logo_entreprise', models.ImageField(upload_to='entreprise_solution_img/')),
                ('telephone_entreprise', models.DecimalField(decimal_places=0, max_digits=13)),
                ('telephone_2_entreprise', models.DecimalField(decimal_places=0, max_digits=13)),
                ('email_entreprise', models.EmailField(max_length=254)),
                ('description_entreprise', models.CharField(max_length=500)),
                ('competence_entreprise', models.CharField(max_length=500)),
                ('sociauFB_entreprise', models.URLField(blank=True, help_text='Copiez le lien de compte Facebook et collez le ici')),
                ('sociauTW_entreprise', models.URLField(blank=True, help_text='Copiez le lien de compte Twitter et collez le ici')),
                ('sociauINS_entreprise', models.URLField(blank=True, help_text='Copiez le lien de compte Instagram et collez le ici')),
                ('sociauIN_entreprise', models.URLField(blank=True, help_text='Copiez le lien de compte LinkedIN et collez le ici')),
            ],
        ),
    ]
