# Generated by Django 3.1.4 on 2021-01-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20201102_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisans_solution',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultance_solution',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise_solution',
            name='site_web',
            field=models.URLField(blank=True),
        ),
    ]
