# Generated by Django 3.1.2 on 2021-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20210218_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisans_solution',
            name='page_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre des vues'),
        ),
        migrations.AddField(
            model_name='consultance_solution',
            name='page_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre des vues'),
        ),
        migrations.AddField(
            model_name='entreprise_solution',
            name='page_vues',
            field=models.IntegerField(default=0, verbose_name='Nombre des vues'),
        ),
    ]
