# Generated by Django 3.1.6 on 2021-02-18 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
