# Generated by Django 3.1.2 on 2020-10-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='resume',
            field=models.TextField(max_length=300),
        ),
    ]
